name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  code-cov:
    name: Code Coverage
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.0'
          args: '--ignore-tests --exclude-files ./src/main.rs --exclude-files ./src/lib.rs --exclude-files ./src/xml_tags/types.rs --release -- --test-threads 4'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.5.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2.2.3
        with:
          name: code-coverage-report
          path: cobertura.xml
